/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './dataplatform/static/**/*.html',
    './dataplatform/static/**/*.js',
  ],
  safelist: [
    // Dynamic color classes generated by JS in job_builder, monitoring, admin, alerts
    { pattern: /^bg-(slate|gray|red|orange|amber|yellow|green|emerald|cyan|blue|indigo|violet|purple|pink)-(50|100|200|300|400|500|600|700|800|900|950)$/ },
    { pattern: /^text-(slate|gray|red|orange|amber|yellow|green|emerald|cyan|blue|indigo|violet|purple|pink)-(50|100|200|300|400|500|600|700|800|900)$/ },
    { pattern: /^border-(slate|gray|red|orange|amber|yellow|green|emerald|cyan|blue|indigo|violet|purple|pink)-(100|200|300|400|500|600|700|800)$/ },
    { pattern: /^ring-(slate|red|amber|emerald|blue|indigo|violet)-(300|400|500)$/ },
    // Opacity variants used in job_builder modals
    'bg-black/50', 'bg-black/60', 'bg-slate-50/50', 'bg-slate-800/60', 'bg-slate-900/60', 'bg-red-500/20',
    // Dynamic widths/heights used in progress bars
    { pattern: /^w-([0-9]+)$/ },
    { pattern: /^h-([0-9]+)$/ },
    // Backdrop blur used in modals
    'backdrop-blur-sm',
  ],
  theme: { extend: {} },
  plugins: [],
}
