apiVersion: v1
kind: Secret
metadata:
  name: dataplatform-secrets
type: Opaque
stringData:
  DATAPLATFORM_USERNAME: replace-me
  DATAPLATFORM_PASSWORD: replace-me
  DATAPLATFORM_SESSION_SECRET: replace-me-with-at-least-32-random-characters
  POSTGRES_DB: dataplatform
  POSTGRES_USER: dataplatform
  POSTGRES_PASSWORD: replace-me
  POSTGRES_URL: postgresql+psycopg2://dataplatform:replace-me@postgres:5432/dataplatform